# Generated by Django 5.1.3 on 2024-11-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
