# Generated by Django 5.1.3 on 2024-11-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuser_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='refresh_token',
        ),
    ]
