# Generated by Django 5.1.3 on 2024-11-24 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='episodeStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainTitle', models.CharField(max_length=50)),
                ('episodeTitle', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('createdDate', models.DateTimeField()),
                ('episodeNumber', models.IntegerField()),
                ('coverPhoto', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='shortStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyTitle', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('createdDate', models.DateTimeField()),
                ('coverPhoto', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
