# Generated by Django 5.1.3 on 2024-11-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortstory',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='shortstory',
            name='coverPhoto',
        ),
        migrations.AlterField(
            model_name='shortstory',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
