# Generated by Django 5.1.3 on 2024-12-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_rename_user_shortstory_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_prompt', models.CharField(max_length=100)),
            ],
        ),
    ]
